drashland/website-v2

docs/drash/v2.x/2_tutorials/3_servers/2_configuration.md
=> fix: issue with markdown heading

pages/index.jsx
=> feat: Add maintainers section

docs/drash/v2.x/2_tutorials/6_services/5_drash_approved_services/rate_limiter.md
Adds `RateLimiterService` documentation
=> feat(drash/v2.x): add rate limiter service docs

docs/drash/v2.x/2_tutorials/2_resources/3_using_dynamic_paths.md, docs/drash/v2.x/2_tutorials/4_requests/7_handling_cookies.md
=> docs(drash/v2.x): Correct leftover v1 code

docs/drash/v2.x/2_tutorials/2_resources/5_serving_static_assets.md
=> feat(drash/v2.x): Add docs on serving static paths

docs/drash/v2.x/2_tutorials/6_services/5_drash_approved_services/dexter.md, docs/drash/v2.x/2_tutorials/6_services/5_drash_approved_services/rate_limiter.md, docs/drash/v2.x/2_tutorials/6_services/5_drash_approved_services/response_time.md
=> docs(drash/v2.x): Add dexter docs

docs/drash/v2.x/2_tutorials/3_servers/2_configuration.md, docs/drash/v2.x/2_tutorials/3_servers/4_error_handling.md, docs/drash/v2.x/2_tutorials/6_services/6_drash_approved_services/dexter.md, src/components/Markdown.jsx
Add tutorials for Drash Error handling https://github.com/drashland/drash/pull/592
=> feat: Drash Error Handling tutorials

src/components/SideBar.jsx
=> fix: Remove API reference link from dmm

docs/drash/v2.x/2_tutorials/3_servers/4_error_handling.md
Adds tutorial on throwing errors in services
=> feat(drash/v2.x): add tutorial on throwing errors in services

docs/drash/v2.x/2_tutorials/2_resources/6_redirections.md
Closes #100 
https://drash-land-git-feat-drashredirections-drash-land.vercel.app/drash/v2.x/tutorials/resources/redirections
=> feat(drash/v2.x): add redirections documentation

docs/drash/v2.x/2_tutorials/3_servers/2_configuration.md
=> fix(drash/v2.x): missing status code assignment

src/components/Layout.jsx, src/components/SideBar.jsx
=> fix: sidebar overlap and hiding on scroll

docs/line/v1.x/2_tutorials/5_options/4_option_values.md
Improves wording for now until #128 is implemented.
=> chore(line/v1.x): improve docs on how to use option values

.github/dependabot.yml, docs/line/v1.x/2_tutorials/5_options/4_option_values.md, package.json, src/services/config_service.js, yarn.lock
Bundles latest dependabot updates to check them all in one preview environment
=> chore: dependabot updates

docs/sinco/v4.x/1_getting_started/2_about_sinco.md
Moves the Acknowledgements section from Sinco repo to here
=> chore(sinco/v4.x): move acknowledgements from repo to here

docs/drash/v2.x/2_tutorials/6_services/4_drash_approved_services/resource_loader.md
Closes https://github.com/drashland/drash/pull/644
=> feat(drash/v2.x): ResourceLoaderService docs

docs/drash/v2.x/2_tutorials/6_services/4_drash_approved_services/graphql.md
Closes https://github.com/drashland/drash/pull/647
=> feat(drash/v2.x): improved graphql docs

README.md, docs/line/v1.x/2_tutorials/2_creating_a_cli/1_single_command_clis/2_part_1_entry_points.md, docs/line/v1.x/2_tutorials/2_creating_a_cli/1_single_command_clis/3_part_2_add_arguments.md, docs/line/v1.x/2_tutorials/2_creating_a_cli/1_single_command_clis/4_part_3_add_an_option.md, docs/line/v1.x/2_tutorials/2_creating_a_cli/2_subcommand_clis/2_part_1_entry_points.md, docs/line/v1.x/2_tutorials/2_creating_a_cli/2_subcommand_clis/3_part_2_add_an_argument.md, docs/line/v1.x/2_tutorials/2_creating_a_cli/2_subcommand_clis/4_part_3_add_an_option.md, docs/line/v1.x/2_tutorials/2_creating_a_cli/2_subcommand_clis/5_part_4_add_a_subcommand.md, docs/line/v1.x/2_tutorials/3_commands/1_main_commands.md, docs/line/v1.x/2_tutorials/3_commands/2_subcommands.md, docs/line/v1.x/2_tutorials/4_arguments/1_introduction.md, docs/line/v1.x/2_tutorials/4_arguments/2_adding_arguments.md, docs/line/v1.x/2_tutorials/5_options/1_introduction.md, docs/line/v1.x/2_tutorials/5_options/2_adding_options.md, docs/line/v1.x/2_tutorials/5_options/3_option_signatures.md, package.json, src/services/content_replacer_service.jsx
=> feat(line/v1.x): use placeholders for steps and import statements

docs/rhum/v2.x/1_getting_started/1_introduction.md, docs/rhum/v2.x/2_tutorials/2_test_doubles/2_fakes.md, docs/rhum/v2.x/2_tutorials/2_test_doubles/3_mocks.md, docs/rhum/v2.x/2_tutorials/2_test_doubles/4_spies/1_class_spies.md
Adds docs for https://github.com/drashland/rhum/pull/172
- [Fakes](https://drash-land-git-rhum-will-return-callback-drash-land.vercel.app/rhum/v2.x/tutorials/test-doubles/fakes)
- [Mocks](https://drash-land-git-rhum-will-return-callback-drash-land.vercel.app/rhum/v2.x/tutorials/test-doubles/mocks)
=> feat(rhum/v2.x): add docs for willReturn() using a callback

docs/drash/v2.x/2_tutorials/3_servers/2_configuration.md, docs/drash/v2.x/2_tutorials/4_requests/configuration.md, docs/drash/v2.x/2_tutorials/4_requests/handling_the_original_request_body.md, src/components/Markdown.jsx
=> feat(drash/v2.x): server.request.read_body

src/components/markdown/CodeExtended.tsx
Clicking code tabs are hella busted
=> fix: code tabs not working

src/components/Layout.tsx
"Last edited" text isn't correct. Removing for now.
=> chore: remove broken last edited text
